#!/bin/bash

Selection="$*"
Name=${Selection%% :*}
Source=${Selection#* :}
Source=${Source%%:*}

case "$Source" in
    man)
        if [[ $Name =~ ^(.+)\ \(([[:alnum:]]+)\)$ ]]; then
            man -Pcat "${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
        else
            man -Pcat "$Name"
        fi
        ;;
    tldr)
        tldr "$Name"
        ;;
    cheat)
        cheat "$Name"
        ;;
    *)
        exit 1
        ;;
esac
